spring.application.name=LifeSync

spring.datasource.url=jdbc:postgresql://localhost:5432/lifesync
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

bring.api.uid=${BRING_API_UID:}
bring.api.key=${BRING_API_KEY:}
bring.client-url=${BRING_CLIENT_URL:http://localhost:5173}
postnord.api.key=${POSTNORD_API_KEY:ac52d1557b344b91f088a000b808ffb9}
postnord.base-url=${POSTNORD_BASE_URL:https://api2.postnord.com/rest}
postnord.locale=${POSTNORD_LOCALE:sv}
lifesync.packages.refresh-delay-ms=${PACKAGE_REFRESH_DELAY_MS:900000}
